name: Backup to Another GitHub Account

on:
  schedule:
    - cron: '0 0 * * *'  # Запуск каждый день в полночь (UTC)
  push:
    branches:
      - main  # Триггер на изменения в главной ветке

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Create backup-repo folder if not exists
        run: mkdir -p backup-repo

      - name: Set up remote repository access
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN_REMOTE }}@github.com/TheZeromy/backup-repo.git

      - name: Commit and push to remote repository
        run: |
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit";
          else
            git commit -m "Backup to another account on $(date)"
            git push origin main
          fi
