name: Daily Backup

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clone the backup repository
        run: git clone https://github.com/7eromy/backup-repo.git backup-repo

      - name: Copy files to backup repository
        run: |
          rsync -av --exclude .git ./ ./backup-repo/

      - name: Commit and push changes
        run: |
          cd backup-repo
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m "Backup on $(date)"
            git push https://x-access-token:${{ secrets.ZEROMY_TOKEN }}@github.com/7eromy/backup-repo.git main
          fi
