name: Backup Repository Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Запуск каждый день в полночь (UTC)
  push:
    branches:
      - main  # Триггер на изменения в главной ветке

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clone the backup repository
        run: |
          git clone https://github.com/7eromy/backup-repo.git backup-repo
        working-directory: ./backup-repo

      - name: Copy files to backup repository
        run: |
          cp -r * ./backup-repo/
        working-directory: .

      - name: Commit and push changes
        run: |
          cd backup-repo
          git add .
          git commit -m "Backup on $(date)"
          git push origin main
        working-directory: ./backup-repo
